export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const GET_ALL_ROOMS_SUCCESS = 'GET_ALL_ROOMS_SUCCESS';
export const GET_ALL_ROOMS_FAIL = 'GET_ALL_ROOMS_FAIL';
